---
 - hosts: datacenter
   sudo: yes
   tasks:
   - name: update the systems
     apt:  update_cache=yes
 - hosts: webservers
   sudo: yes
   tasks:
   - name: install web related packages
     apt:  state=present name={{ item }}
     with_items:
     - git
     - nginx
     - lynx
     - nano
 - hosts: dbservers
   sudo: yes
   tasks:
   - name: install packages to setup dbservers
     apt:  state=present name=git-core
   - name: add gpg key for mongodb
     apt_key:
       keyserver: keyserver.ubuntu.com
       id: 0C49F3730359A14518585931BC711F9BA15703C6
   - name: add mongo repository
     apt_repository:
       repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
       state: present
   - name: install mongodb packages
     apt: 
         name: mongodb-org
         update_cache: yes 


#     when: ansible1_os_family == 'Debian'